In [2]:
import math
import numpy as np
import tensorflow as tf
import pandas as pd
import h5py
from tensorflow.python.framework import ops
from tf_utils import load_dataset, random_mini_batches, convert_to_one_hot, predict

%matplotlib inline
np.random.seed(1)

In [3]:
y_hat=tf.constant(36,name='y_hat')
y=tf.constant(39,name='y')
loss=tf.Variable((y-y_hat)**2,name='loss')
init=tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print (sess.run(loss))

9


In [15]:
def sigmoid(z):
    x = tf.placeholder(tf.float32, name="x")
    sigmoid=tf.sigmoid(x)
    with tf.Session() as sess: 
        result = sess.run(sigmoid, feed_dict = {x: z})
    return result

In [16]:
sigmoid(0.5)

0.62245935

In [17]:
def cost(logits,labels):
    z=tf.placeholder(tf.float32,name="z")
    y=tf.placeholder(tf.float32,name="y")
    cost=tf.nn.sigmoid_cross_entropy_with_logits(logits=z,labels=y)
    sess=tf.Session()
    cost=sess.run(cost,feed_dict={z:logits,y:labels})
    sess.close()
    return cost

In [18]:
logits = sigmoid(np.array([0.2, 0.4, 0.7, 0.9]))
cost = cost(logits, np.array([0, 0, 1, 1]))
print (cost)

[ 1.00538719  1.03664088  0.41385433  0.39956614]


In [19]:
def one_hot_matrix(labels,C):
    c=tf.constant(C,name="c")
    one_hot_matrix=tf.one_hot(indices=labels,depth=c,axis=0)
    sess=tf.Session()
    one_hot=sess.run(one_hot_matrix)
    sess.close()
    
    return one_hot

In [20]:
labels = np.array([1,2,3,0,2,1])
one_hot = one_hot_matrix(labels,4)

In [21]:
print (one_hot)

[[ 0.  0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.]]
